keys:
  - &kat_timberhearth age1mxnzal4n5yqjj4njglk84csnjz25zen9nzjkdq8z78960c44geqq7kdgkp
  - &timberhearth age1veq2hqysf2792dq2zwrz9ud0gsvtjlm5uyaj48j4fsk2x3seu9sskr6pad
  - &kat_solarsystem  age1s8dmj6tn4gcew0ccekuyymvs2r8dwwtvkfezam27stj90q6qdy2qj8wyta
  - &solarsystem age18sx7e8ngq5l0t60ss7cyp6ywuksc2ud5rqj4h307lw8xg77jssksxcydzu
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *kat_timberhearth
          - *kat_solarsystem
          - *timberhearth
          - *solarsystem
